/*
 * Copyright 2020 Acoustic, L.P.
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Apache License, Version 2.0
 * www.apache.org
 * Home page of The Apache Software Foundation
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 */

package co.acoustic.content.delivery.sdk;

import org.json.JSONObject;

import java.util.ArrayList;

class DeliverySearchResponseDocument {
    /**
     * For pages, this field contains the IDs that the page's appearance is made up of.
     * This comprises the page's ID as well as the IDs of the page content item and it's directly referenced content items.
     * Changes in one of those items will cause the page to be re-indexed.
     */
    ArrayList<String> aggregatedIds;

    /**
     * For pages, this field contains the content IDs that the page's appearance is made up of.
     * This comprises the IDs of the page content item and it's directly referenced content items.
     * Changes in one of those items will cause the page to be re-indexed.
     */
    ArrayList<String> aggregatedContentIds;

    /**
     * For assets, this field contains the asset type. The value that is returned can be "document", "file", "image", or "video".
     */
    String assetType;

    /**
     * For content, this field can contain boolean element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    ArrayList<Boolean> boolean1;

    /**
     * For content, this field can contain boolean element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    ArrayList<Boolean> boolean2;

    /**
     * The list of all category selections for the asset or content.
     * All category selection elements on content are merged into this property.
     */
    ArrayList<String> categories;

    /**
     * The list of all leaf category selection elements for the asset or content.
     */
    ArrayList<String> categoryLeaves;

    /**
     * This field describes the kind of item. The value that is returned can be "asset", "category", "content" or "taxonomy".
     */
    String classification;

    /**
     * The creation date of the item.
     * <p>
     * Examples:
     * <ul>
     * <li>2020-01-07T17:52:31.610Z</li>
     * <li>2020-01-07T17:52:31.477Z</li>
     * <li>2020-01-07T17:52:31.828Z</li>
     * </ul>
     */
    String created;

    /**
     * The UUID of the user that created the item.
     */
    String creatorId;

    /**
     * For content, this field can contain date element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     * <p>
     * Examples:
     * <ul>
     * <li>2020-01-07T17:52:31.610Z</li>
     * <li>2020-01-07T17:52:31.477Z</li>
     * <li>2020-01-07T17:52:31.828Z</li>
     * </ul>
     */
    ArrayList<String> date1;

    /**
     * For content, this field can contain date element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     * <p>
     * Examples:
     * <ul>
     * <li>2020-01-07T17:52:31.610Z</li>
     * <li>2020-01-07T17:52:31.477Z</li>
     * <li>2020-01-07T17:52:31.828Z</li>
     * </ul>
     */
    ArrayList<String> date2;

    /**
     * The description of the item.
     */
    String description;

    /**
     * For assets and content, this field contains the full JSON document for the item.
     */
    JSONObject document;

    /**
     * For assets, this field contains the file size in bytes.
     */
    long fileSize;

    /**
     * For content, this field contains the list of path values related to files that are generated by pre-rendering the item.
     */
    ArrayList<String> generatedFiles;

    /**
     * For images, this field contains the height.
     */
    int height;

    /**
     * For pages, this field specifies whether it should be hidden from navigation controls.
     */
    boolean hideFromNavigation;

    /**
     * The identifier of the item. For items of the same "classification", this identifier is unique.
     * The combination of the "classification" and the "id" is unique across all items of the Watson Content Hub tenant.
     */
    String id;

    /**
     * For assets and content, this field specifies whether the content is managed or not managed and whether the asset is a managed asset or a so-called non-managed web asset.
     */
    boolean isManaged;

    /**
     * The list of keywords related to the item.
     */
    ArrayList<String> keywords;

    /**
     * For pages, this field contains all kinds a page is assigned to.
     */
    ArrayList<String> kind;

    /**
     * The last modification date of the item.
     * <p>
     * Examples:
     * <ul>
     * <li>2020-01-07T17:52:31.610Z</li>
     * <li>2020-01-07T17:52:31.477Z</li>
     * <li>2020-01-07T17:52:31.828Z</li>
     * </ul>
     */
    String lastModified;

    /**
     * The UUID of the user that last modified the item.
     */
    String lastModifierId;

    /**
     * The language for which the item was created.
     */
    String locale;

    /**
     * For assets, this field contains the folder path without the file name.
     * This allows for efficient queries for sibling assets.
     */
    String location;

    /**
     * For content, this field contains an array of strings.
     * Each string consists of the latitude and the longitude of location elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    ArrayList<String> location1;

    /**
     * For assets, this field contains all of the path segments.
     * This allows for efficient queries that return assets in subfolders of the queried value.
     * For example, the query locationPaths:"/dxdam" will return assets that are stored in the /dxdam folder or any subfolder.
     */
    String locationPaths;

    /**
     * For content, this field contains an array of strings.
     * Each string consists of the latitude and the longitude of a Location element of the content item.
     * For example, this field contains ["48.666259, 9.039273", "53.418880, -6.416081"] for a content item with two Location elements.
     */
    ArrayList<String> locations;

    /**
     * For assets, this field contains the URL to the binary of the asset.
     * It is relative to the API URL for your tenant.
     */
    String media;

    /**
     * For assets, this field contains the media type.
     */
    String mediaType;

    /**
     * The name of the item.
     */
    String name;

    /**
     * For content, this field can contain number element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    ArrayList<Double> number1;

    /**
     * For content, this field can contain number element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    ArrayList<Double> number2;

    /**
     * For pages, this field contains the ID of the parent page.
     */
    String parentId;

    /**
     * For assets, this field contains the folder path including file name.
     */
    String path;

    /**
     * For pages, this field contains the position of the page relative to it's sibling pages.
     */
    int position;

    /**
     * For assets, this field contains the ID of the related resource.
     * You can use this resource ID with the authoring and delivery resource service REST APIs.
     */
    String resource;

    /**
     * This field specifies whether the item is restricted.
     */
    boolean restricted;

    /**
     * For pages, this field contains the ID of the site the page belongs to.
     */
    String siteId;

    /**
     * For assets and content, this field contains the state the item is in.
     * The value of this field can be "ready" or "retired".
     */
    String status;

    /**
     * For content, this field can contain string element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    ArrayList<String> string1;

    /**
     * For content, this field can contain string element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    ArrayList<String> string2;

    /**
     * For content, this field can contain string element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    ArrayList<String> string3;

    /**
     * For content, this field can contain string element values for elements mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    ArrayList<String> string4;

    /**
     * For content, this field can contain a single date element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    String sortableDate1;

    /**
     * For content, this field can contain a single date element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    String sortableDate2;

    /**
     * For content, this field can contain a single number element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    Double sortableNumber1;

    /**
     * For content, this field can contain a single number element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    Double sortableNumber2;

    /**
     * For content, this field can contain a single string element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    String sortableString1;

    /**
     * For content, this field can contain a single string element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    String sortableString2;

    /**
     * For content, this field can contain a single string element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    String sortableString3;

    /**
     * For content, this field can contain a single string element value for an element mapped to this field.
     * The mapping of elements to search fields is defined in the content type referenced by the content item.
     */
    String sortableString4;

    /**
     * The list of tags assigned to the item.
     */
    ArrayList<String> tags;

    /**
     * For content, this field is a collection of field names and text fragments that make up the item.
     * It facilitates full-text search.
     */
    ArrayList<String> text;

    /**
     * For assets, this field contains the URL to the thumbnail of the asset.
     * It is relative to the API URL for your tenant.
     */
    String thumbnail;

    /**
     * For content, this field contains the name of the content type.
     */
    String type;

    /**
     * For content, this field contains the ID of the content type.
     */
    String typeId;

    /**
     * For assets, this field contains the server relative URL to the binary document of the asset.
     * For pages, it contains the URL under which the page can be adressed in an SPA.
     */
    String url;

    /**
     * For images, this field contains the width.
     */
    int width;
}
